pub const FIGHTER_NESS_STATUS_SPECIAL_HI_FLAG_AIR_LASSO_FAIL: i32 = 0x21000012;
pub const WEAPON_NESS_YOYO_STATUS_KIND_REACH: i32 = 0x7;
pub const WEAPON_NESS_YOYO_STATUS_KIND_REWIND: i32 = 0x3;
pub const WEAPON_NESS_YOYO_STATUS_KIND_HANG: i32 = 0x6;
pub const WEAPON_NESS_YOYO_STATUS_KIND_EXHAUST: i32 = 0x2;
pub const WEAPON_NESS_YOYO_STATUS_KIND_WAIT: i32 = 0x0;
/*
    WEAPON_SAMUS_GBEAM_STATUS_KIND_EXHAUST: 0x2,
    WEAPON_SAMUS_GBEAM_STATUS_KIND_HANG_REWIND: 0x6,
    WEAPON_SAMUS_GBEAM_STATUS_KIND_NUM: 0x9,
    WEAPON_SAMUS_GBEAM_STATUS_KIND_PULL: 0x4,
    WEAPON_SAMUS_GBEAM_STATUS_KIND_REACH: 0x7,
    WEAPON_SAMUS_GBEAM_STATUS_KIND_REWIND: 0x3,
    WEAPON_SAMUS_GBEAM_STATUS_KIND_SHOOT: 0x1,
    WEAPON_SAMUS_GBEAM_STATUS_KIND_WAIT: 0x0,
*/

pub const WEAPON_NESS_YOYO_HEAD_STATUS_KIND_LASSO: i32 = 0x4;

pub const GENERATE_ARTICLE_LAST: i32 = 0x8;
pub static mut GENERATE_ARTICLE_GRAPPLE: i32 = 0x0;